# Generated by Django 2.1.1 on 2018-10-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=2000)),
                ('pid', models.CharField(max_length=3005)),
            ],
            options={
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='MySiteProduct',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('proname', models.TextField()),
                ('prodes', models.TextField()),
                ('proimg', models.CharField(max_length=300)),
                ('proprice', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='MySiteUser',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=200)),
                ('upass', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
