# Generated by Django 2.1.1 on 2018-10-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quan',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
