# Generated by Django 2.1.1 on 2018-11-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20181025_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysiteuser',
            name='uemail',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
