# Generated by Django 2.1.1 on 2018-11-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='cdes',
            field=models.CharField(default='', max_length=400),
        ),
    ]
