# Generated by Django 2.1.1 on 2018-11-12 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_coupon_cdes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
